---
title: "Analysis of Covariate Results"
author: "Lauren Khoury"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

R script for analysis
this script will:
  - concatenate all results csv files saved from CHTC into one dataframe
  - calculate what percentage of results has p < 0.05
  - group data by research setting
  - calculate the type I and type II error rates for when b_x is zero vs nonzero
  - visualize the sampling distribution of X effect

```{r set up}

# load packages + set ggplot theme

library(dplyr)
library(skimr)
library(purrr)
library(ggplot2)

theme_set(theme_classic())

# format path 

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
rdrive_path <- format_path("cov/raw_data")

```

```{r read in data}

jobs <- read.csv("jobs.csv", header = FALSE,
                 col.names = c("job_num", "n_sims", "n_obs", "b_x", 
                               "n_covs", "b_cov", "p_good_covs", "r_cov")) |> 
  glimpse()

data <- read.csv(here::here(rdrive_path, "batch_results.csv")) |> 
  mutate(model = gsub("[ -]", "_", model)) |> 
  glimpse()

```

```{r prop sig}

data |> group_by(model) |> summarise(prop_sig = mean(p_value < 0.05))

```

```{r function plot hist dens}

plot_hist_density <- function(data, model_name) {
  ggplot(data |> filter(model == model_name), aes(x = estimate)) +
    geom_histogram(aes(y = after_stat(density)), bins = 10, fill = "grey", color = "black") +
    geom_density(fill = "blue", alpha = 0.25, lwd = 1) + 
    labs(title = paste("Density Plot:", model_name), x = "Beta_X Estimate", y = "Density")
}

```

```{r plot hist dens}

plot_hist_density(data, "lm_no_covs")
plot_hist_density(data, "lm_all_covs")
plot_hist_density(data, "lm_p_hacked")
plot_hist_density(data, "lm_partial_r")

```
