---
title: "Supplemental Material"
date: last-modified
number-sections: true
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 5
execute:
  echo: false
editor_options: 
  chunk_output_type: console
---

This file contains the supplemental materials for *Title of paper*. It includes all supplemental figures and tables. Additional materials are made available on our study's OSF page ([https://osf.io/zh5gn/](https://osf.io/zh5gn/)).   

-----

```{r}
#| label: set up

suppressMessages(suppressWarnings(library(tidyverse)))
suppressWarnings(library(patchwork))
suppressWarnings(library(kableExtra, exclude = ("group_rows"))) 

theme_set(theme_classic())

path_processed <- "\\\\research.drive.wisc.edu\\jjcurtin\\studydata\\cov\\data_processed"

d <- read_csv(here::here(path_processed, "results_tibble.csv"),
              show_col_types = FALSE)

d_full <- read_csv(here::here(path_processed, "results_combined_raw.csv"),
              show_col_types = FALSE)

```


### Type I error

#### b effect = 0

```{r}
#| warning: TRUE 

d_0 <- d |> 
  filter(b_x == 0) |> 
  select(-type_II, -b_x) |> 
  pivot_wider(names_from = method, values_from = type_I) |> 
  select(`n obs` = n_obs, `n covs` = n_covs, `r ycov` = r_ycov, 
         `prop good covs` = p_good_covs, `no covs` = no_covs, `all covs` = all_covs,
         `p-hacking` = p_hacked, `single cov lm w/o x` = r, 
         `single cov lm w/x` = partial_r, 
         `all cov lm w/o x` = full_lm_wo_x, `all cov lm w/x` = full_lm,
         `all cov lasso w/o x` = lasso_wo_x, `all cov lasso w/x` = lasso)

d_0 |> 
  kable(caption = "Type I error rates for b effect = 0 by method and research context", 
        digits = 3,
        col.names = c("n obs", "n covs", "r ycov", "prop good covs",
                      "no covs", "all covs", "p-hack", "w/o X", "w/X",
                      "w/o X", "w/X", "w/o X", "w/X"),
        table.attr = "style='table-layout: fixed;'") |> 
  kable_styling(full_width = FALSE) |>
  column_spec(1:ncol(d_0), width = "10em") |> 
  row_spec(row = 0, bold = TRUE) |> 
  add_header_above(c(" " = 7,
                     "Single cov lm" = 2,
                     "All cov lm" = 2,
                     "All cov LASSO" = 2),
                   bold = TRUE) |>
  add_header_above(c("Research Context" = 4,
                     "A Priori Selection" = 2,
                     "Data-driven Selection" = 7),
                   bold = TRUE) |>
  scroll_box(width = "100%", height = "800px") |> 
  suppressWarnings()
```



### Type II error

#### b effect = 0.2

```{r}
#| warning: false

d_02 <- d |> 
  filter(b_x == 0.2) |> 
  select(-type_I, -b_x) |> 
  pivot_wider(names_from = method, values_from = type_II) |> 
  select(`n obs` = n_obs, `n covs` = n_covs, `r ycov` = r_ycov, 
         `prop good covs` = p_good_covs, `no covs` = no_covs, `all covs` = all_covs,
         `p-hacking` = p_hacked, `single cov lm w/o x` = r, 
         `single cov lm w/x` = partial_r, 
         `all cov lm w/o x` = full_lm_wo_x, `all cov lm w/x` = full_lm,
         `all cov lasso w/o x` = lasso_wo_x, `all cov lasso w/x` = lasso)

d_02 |> 
  kable(caption = "Type II error rates for b effect = 0.2 by method and research context", 
        digits = 3,
        col.names = c("n obs", "n covs", "r ycov", "prop good covs",
                      "no covs", "all covs", "p-hack", "w/o X", "w/X",
                      "w/o X", "w/X", "w/o X", "w/X"),
        table.attr = "style='table-layout: fixed;'") |> 
  kable_styling(full_width = FALSE) |>
  column_spec(1:ncol(d_0), width = "10em") |> 
  row_spec(row = 0, bold = TRUE) |> 
  add_header_above(c(" " = 7,
                     "Single cov lm" = 2,
                     "All cov lm" = 2,
                     "All cov LASSO" = 2),
                   bold = TRUE) |>
  add_header_above(c("Research Context" = 4,
                     "A Priori Selection" = 2,
                     "Data-driven Selection" = 7),
                   bold = TRUE) |>
  scroll_box(width = "100%", height = "800px") |> 
  suppressWarnings()
```

#### b effect = 0.5

```{r}
#| warning: false

d_05 <- d |> 
  filter(b_x == 0.5) |> 
  select(-type_I, -b_x) |> 
  pivot_wider(names_from = method, values_from = type_II) |> 
  select(`n obs` = n_obs, `n covs` = n_covs, `r ycov` = r_ycov, 
         `prop good covs` = p_good_covs, `no covs` = no_covs, `all covs` = all_covs,
         `p-hacking` = p_hacked, `single cov lm w/o x` = r, 
         `single cov lm w/x` = partial_r, 
         `all cov lm w/o x` = full_lm_wo_x, `all cov lm w/x` = full_lm,
         `all cov lasso w/o x` = lasso_wo_x, `all cov lasso w/x` = lasso)

d_05 |> 
  kable(caption = "Type II error rates for b effect = 0.5 by method and research context", 
        digits = 3,
        col.names = c("n obs", "n covs", "r ycov", "prop good covs",
                      "no covs", "all covs", "p-hack", "w/o X", "w/X",
                      "w/o X", "w/X", "w/o X", "w/X"),
        table.attr = "style='table-layout: fixed;'") |> 
  kable_styling(full_width = FALSE) |>
  column_spec(1:ncol(d_0), width = "10em") |> 
  row_spec(row = 0, bold = TRUE) |> 
  add_header_above(c(" " = 7,
                     "Single cov lm" = 2,
                     "All cov lm" = 2,
                     "All cov LASSO" = 2),
                   bold = TRUE) |>
  add_header_above(c("Research Context" = 4,
                     "A Priori Selection" = 2,
                     "Data-driven Selection" = 7),
                   bold = TRUE) |>
  scroll_box(width = "100%", height = "800px") |> 
  suppressWarnings()
```





### Parameter Estimates

```{r}
method_colors <- c("No covariates" = "#FF7D00",
                   "All covariates" = "#9E5900",
                   "p-hacking" = "#C92C04",
                   "Single covariate lm" = "#5489BA",
                   "Single covariate lm with X" = "#5489BA",
                   "All covariates lm" = "#664896",
                   "All covariates lm with X" = "#664896",
                   "All covariates LASSO" = "#4A7C59",
                   "All covariates LASSO with X" = "#4A7C59")


method_linetypes <- c("No covariates" = "solid",
                     "All covariates" = "solid",
                     "p-hacking" = "solid",
                     "Single covariate lm" = "dashed",
                     "Single covariate lm with X" = "solid",
                     "All covariates lm" = "dashed",
                     "All covariates lm with X" = "solid",
                     "All covariates LASSO" = "dashed",
                     "All covariates LASSO with X" = "solid")


d_full <- d_full |> 
  mutate(method = factor(method, 
                          levels = c("no_covs", "all_covs","p_hacked",  "r",
                                      "partial_r", "full_lm_wo_x", "full_lm",  
                                      "lasso_wo_x", "lasso"),
                         labels = c("No covariates", "All covariates", "p-hacking", 
                                    "Single covariate lm", "Single covariate lm with X", 
                                    "All covariates lm", "All covariates lm with X", 
                                    "All covariates LASSO", "All covariates LASSO with X")))

```


```{r}

est_d_0 <- d_full |> 
  filter(b_x == 0) |> 
  filter(estimate > -0.5 & estimate < .5) |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black") +
  scale_x_continuous(limits = c(-0.5, 0.5), breaks = seq(-0.5, 0.5, by = 0.5)) +
  labs(y = "Density",
       x = "Estimate") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) 

est_d_02 <-d_full |> 
  filter(b_x == 0.2) |> 
  filter(estimate > -0.3 & estimate < .7) |> 
  filter(method != "p-hacking") |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0.2, linetype = "dotted") +
  scale_x_continuous(limits = c(-0.3, 0.7), breaks = c(-0.3, 0.2, 0.7)) +
  labs(y = "Density",
       x = "Estimate") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  theme(legend.position = "none")

est_d_05 <- d_full |> 
  filter(b_x == 0.5) |> 
  filter(estimate > 0 & estimate < 1) |> 
  filter(method != "p-hacking") |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0.5, linetype = "dotted") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  labs(y = "Density",
       x = "Estimate") + 
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  theme(legend.position = "none")
```

```{r}
#| label: fig-distribution-bx
#| fig-cap: "Sampling Distribution for Population Parameter Estimates."
#| fig-height: 8

est_d_0 / est_d_02 / est_d_05
```


