---
title: "Calculate summary stats"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
execute:
  echo: false
html-table-processing: none
---

```{r}
#| label: set up

library(tidyverse)

# devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true") |> suppressMessages()

# rdrive_path <- format_path("cov/raw_data")

rdrive_path <- "\\\\research.drive.wisc.edu\\jjcurtin\\studydata\\cov\\raw_data"


options(digits = 3)

```

```{r}
#| label: read in data

d_0 <- data.table::fread(here::here(rdrive_path, "batch_results_new_method_0.csv"))
d_05 <- data.table::fread(here::here(rdrive_path, "batch_results_new_method_05.csv"))

d_20_covs <- data.table::fread(here::here(rdrive_path, "batch_results_20_covs.csv"))
d_n50 <- data.table::fread(here::here(rdrive_path, "batch_results_n50.csv"))

d2_0 <- data.table::fread(here::here(rdrive_path, "batch_results_new_20K_0.csv"))
d2_05 <- data.table::fread(here::here(rdrive_path, "batch_results_new_20K_05.csv"))

d_wo_x_0 <- data.table::fread(here::here(rdrive_path, "batch_results_methods_wo_x_seed0.csv"))
d_wo_x_1 <- data.table::fread(here::here(rdrive_path, "batch_results_methods_wo_x_seed1.csv"))

d_02_0 <- data.table::fread(here::here(rdrive_path, "batch_results_02_seed0.csv"))
d_02_1 <- data.table::fread(here::here(rdrive_path, "batch_results_02_seed1.csv"))

```

```{r}
#| label: combine data

d_0 <- rbind(d_0, d_20_covs |> filter(b_x == 0))
d_0 <- rbind(d_0, d_n50 |> filter(b_x == 0))

d_05 <- rbind(d_05, d_20_covs |> filter(b_x == 0.5))
d_05 <- rbind(d_05, d_n50 |> filter(b_x == 0.5))

rm(d_20_covs, d_n50)

d_0 <- rbind(d_0, d2_0)
d_05 <- rbind(d_05, d2_05)

rm(d2_0, d2_05)

d_0 <- rbind(d_0, d_wo_x_0 |> filter(b_x == 0))
d_0 <- rbind(d_0, d_wo_x_1 |> filter(b_x == 0))

d_05 <- rbind(d_05, d_wo_x_0 |> filter(b_x == 0.5))
d_05 <- rbind(d_05, d_wo_x_1 |> filter(b_x == 0.5))

rm(d_wo_x_0, d_wo_x_1)

d_02 <- rbind(d_02_0, d_02_1)

rm(d_02_0, d_02_1)

```


### P-Hacking stats 

Simmons comparison (N = 50, n-covs = 4)
```{r}
d_0 |> 
  filter(method == "p-hacking" & n_obs == 50 & n_covs == 4)  |> 
  group_by(simulation_id) |> 
  summarise(type_I = mean(p_value < 0.05), .groups = "drop") |> 
  summarise(mean(type_I),
            min(type_I),
            max(type_I))
```


8-12 covs
```{r}
d_0 |> 
  filter(method == "p-hacking" & n_obs == 50 & n_covs %in% c(8, 12))  |> 
  group_by(simulation_id, n_covs) |> 
  summarise(type_I = mean(p_value < 0.05), .groups = "drop") |> 
  summarise(mean(type_I),
            min(type_I),
            max(type_I))
```

16-20 covs
```{r}
d_0 |> 
  filter(method == "p-hacking" & n_obs == 50 & n_covs %in% c(16, 20))  |> 
  group_by(simulation_id, n_covs) |> 
  summarise(type_I = mean(p_value < 0.05), .groups = "drop") |> 
  summarise(mean(type_I),
            min(type_I),
            max(type_I))
```


```{r}
# d_02 <- rbind(d_02, d_05)
# 
# rm(d_05)
# 
# d_all <- d_02 |>
#   filter(method != "p-hacking")
# 
# 
# d_all |> 
#   filter(n_obs == 50)  |> 
#   group_by(simulation_id, method) |> 
#   summarise(type_II = mean(p_value >= 0.05), .groups = "drop") |> 
#   group_by(method) |> 
#   summarise(mean(type_II)) 
# 
# d_all |> 
#   filter(n_covs == 20)  |> 
#   group_by(simulation_id, method) |> 
#   summarise(type_II = mean(p_value >= 0.05), .groups = "drop") |> 
#   group_by(method) |> 
#   summarise(mean(type_II)) 
```


