---
title: "Make results tibble"
date: last-modified
number-sections: true
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 5
execute:
  echo: false
editor_options: 
  chunk_output_type: console
---

This script makes `results_tibble.csv` and `estimate_tibble.csv`


```{r}
#| label: read in data
#| code-fold: true

library(tidyverse)

path_raw <- "\\\\research.drive.wisc.edu\\jjcurtin\\studydata\\cov\\data_raw"
path_processed <- "\\\\research.drive.wisc.edu\\jjcurtin\\studydata\\cov\\data_processed"

d_0 <- data.table::fread(here::here(path_raw, "batch_results_new_method_0.csv"))
d_05 <- data.table::fread(here::here(path_raw, "batch_results_new_method_05.csv"))

d_20_covs <- data.table::fread(here::here(path_raw, "batch_results_20_covs.csv"))
d_n50 <- data.table::fread(here::here(path_raw, "batch_results_n50.csv"))

d2_0 <- data.table::fread(here::here(path_raw, "batch_results_new_20K_0.csv"))
d2_05 <- data.table::fread(here::here(path_raw, "batch_results_new_20K_05.csv"))

d_wo_x_0 <- data.table::fread(here::here(path_raw, "batch_results_methods_wo_x_seed0.csv"))
d_wo_x_1 <- data.table::fread(here::here(path_raw, "batch_results_methods_wo_x_seed1.csv"))

d_02_0 <- data.table::fread(here::here(path_raw, "batch_results_02_seed0.csv"))
d_02_1 <- data.table::fread(here::here(path_raw, "batch_results_02_seed1.csv"))

```

```{r}
d_0 <- d_0 |> 
  bind_rows(subset(d_20_covs, b_x == 0)) |> 
  bind_rows(subset(d_n50, b_x == 0)) |> 
  bind_rows(subset(d_wo_x_0, b_x == 0)) |> 
  bind_rows(subset(d_wo_x_1, b_x == 0)) |> 
  bind_rows(d2_0)

d_05 <- d_05 |> 
  bind_rows(subset(d_20_covs, b_x == 0.5)) |> 
  bind_rows(subset(d_n50, b_x == 0.5)) |> 
  bind_rows(subset(d_wo_x_0, b_x == 0.5)) |> 
  bind_rows(subset(d_wo_x_1, b_x == 0.5)) |> 
  bind_rows(d2_05)
  
d_02 <- d_02_0 |> 
  bind_rows(d_02_1)


rm(d_20_covs, d_n50, d2_0, d2_05, d_02_0, d_02_1, d_wo_x_0, d_wo_x_1)
```


Combine and save out combined data
```{r}
d_all <- d_0 |> 
  rbind(d_02, d_05) |> 
  glimpse()

d_all |> 
  write_csv(here::here(path_processed, "results_combined_raw.csv"))
```


### Calculate type 1 and type 2 error

Calculate error rates
```{r}
d_tibble <- d_all |> 
  group_by(method, n_obs, n_covs, r_ycov, p_good_covs, b_x) |> 
  summarise(type_I = mean(p_value < 0.05),
            type_II = mean(p_value >= 0.05),
            .groups = "drop")

d_tibble <- d_tibble|> 
  mutate(type_I = if_else(b_x != 0.0, NA_real_, type_I),
         type_II = if_else(b_x == 0.0, NA_real_, type_II))
```

Save out tibble
```{r}
d_tibble |> 
  write_csv(here::here(path_processed, "results_tibble.csv"))
```

### Create Parameter Estimate summary table

```{r}
d_param <- d_all |> 
  group_by(method, b_x) |> 
  summarise(mean = mean(estimate), .groups = "drop") |> 
  pivot_wider(names_from = b_x, values_from = mean)  |> 
  glimpse()

d_param |> 
  write_csv(here::here(path_processed, "estimate_tibble.csv"))
```


