---
title: "Make Figures for Main Manuscript"
author: "Lauren Khoury and Kendra Wyant"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
execute:
  echo: false
html-table-processing: none
---

```{r}
library(tidyverse)
library(patchwork)
library(ggpattern)

path_processed <- "\\\\research.drive.wisc.edu\\jjcurtin\\studydata\\cov\\data_processed"

d <- read_csv(here::here(path_processed, "results_tibble.csv"),
              show_col_types = FALSE)

d_full <- read_csv(here::here(path_processed, "results_combined_raw.csv"),
              show_col_types = FALSE)

d_full <- d_full |> 
  mutate(method = factor(method, 
                          levels = c("no_covs", "all_covs","p_hacked",  "r",
                                      "partial_r", "full_lm_wo_x", "full_lm",  
                                      "lasso_wo_x", "lasso"),
                         labels = c("No covariates", "All covariates", "p-hacking", 
                                    "Separate covariate lm", "Separate covariate lm with X", 
                                    "Simultaneous covariate lm", "Simulataneouis covariate lm with X", 
                                    "Simultaneous covariate LASSO", "Simultaneous covariate LASSO with X")))

options(digits = 3)
theme_set(theme_classic())


method_colors <- c("No covariates" = "#FF7D00",
                   "All covariates" = "#9E5900",
                   "p-hacking" = "#C92C04",
                   "Separate covariate lm" = "#5489BA",
                   "Separate covariate lm with X" = "#5489BA",
                   "Simultaneous covariate lm" = "#664896",
                   "Simultaneous covariate lm with X" = "#664896",
                   "Simultaneous covariate LASSO" = "#4A7C59",
                   "Simultaneous covariate LASSO with X" = "#4A7C59")


method_linetypes <- c("No covariates" = "solid",
                     "All covariates" = "solid",
                     "p-hacking" = "solid",
                     "Separate covariate lm" = "dashed",
                     "Separate covariate lm with X" = "solid",
                     "Simultaneous covariate lm" = "dashed",
                     "Simultaneous covariate lm with X" = "solid",
                     "Simultaneous covariate LASSO" = "dashed",
                     "Simultaneous covariate LASSO with X" = "solid")

method_linewidths <- c("No covariates" = .75,
                     "All covariates" = .75,
                     "p-hacking" = .5,
                     "Separate covariate lm" = .5,
                     "Separate covariate lm with X" = .5,
                     "Simultaneous covariate lm" = .5,
                     "Simultaneous covariate lm with X" = .5,
                     "Simultaneous covariate LASSO" = .5,
                     "Simultaneous covariate LASSO with X" = .5)

method_patterns <- c("No covariates" = "none",
                     "All covariates" = "none",
                     "p-hacking" = "none",
                     "Separate covariate lm" = "stripe",
                     "Separate covariate lm with X" = "none",
                     "Simultaneous covariate lm" = "stripe",
                     "Simultaneous covariate lm with X" = "none",
                     "Simultaneous covariate LASSO" = "stripe",
                     "Simultaneous covariate LASSO with X" = "none")
```



```{r}
d <- d |> 
   mutate(method = factor(method, 
                          levels = c("no_covs", "all_covs","p_hacked",  "r",
                                            "partial_r", "full_lm_wo_x", "full_lm",  
                                           "lasso_wo_x", "lasso"),
                         labels = c("No covariates", "All covariates", "p-hacking", 
                                    "Separate covariate lm", "Separate covariate lm with X", 
                                    "Simultaneous covariate lm", "Simultaneous covariate lm with X", 
                                    "Simultaneous covariate LASSO", "Simultaneous covariate LASSO with X")))

d_0 <- d |> 
  filter(b_x == 0) 
 

d_02 <- d |> 
  filter(b_x == .2)
  
d_05 <- d |> 
 filter(b_x == .5)

```

```{r}
type_I_summary <- d_0 |>
  group_by(method) |>
  summarise(type_I = mean(type_I, .groups = "drop")) |> 
  mutate(group = case_match(method,
                            "p-hacking" ~ "p-hacking",
                            "No covariates" ~ "No selection",
                            "All covariates" ~ "No selection",
                            "Separate covariate lm" ~ "Separate covariate lm",
                            "Separate covariate lm with X" ~ "Separate covariate lm",
                            "Simultaneous covariate lm" ~ "Simultaneous covariate lm",
                            "Simultaneous covariate lm with X" ~ "Simultaneous covariate lm",
                            "Simultaneous covariate LASSO" ~ "Simultaneous covariate LASSO",
                            "Simultaneous covariate LASSO with X" ~ "Simultaneous covariate LASSO"))

```


```{r}
#| label: fig-bar-1
#| fig-cap: "Type I Error by Method. Average type I error rate across all research contexts is displayed for each method separately by color. A priori selection methods are on the left, data-driven selection methods are on the right. Striped shading indicates data-driven selection methods that do not control for X."
#| fig-width: 8.75


# ---- Parameters
gap_after_idx <- c(2,  3, 5, 7)  
gap_size <- 0.2                
bar_width <- 0.9                


df <- type_I_summary |>
  mutate(method_chr = as.character(method))


n <- nrow(df)
base_pos <- seq_len(n)  

# compute how many gaps precede each bar
gap_count_before <- sapply(base_pos, function(i) sum(gap_after_idx < i))
# add the total gap length before each bar
x_pos <- base_pos + gap_count_before * gap_size

plot_df <- df |>
  mutate(x_pos = x_pos)


x_breaks <- plot_df$x_pos
x_labels <- c("No covariates", "All covariates", "p-hacking", 
              "Without X", "With X",
              "Without X", "With X",
              "Without X", "With X")

segment_labels <- tibble::tibble(
  x = c(mean(c(0.5, 2.6)),
        mean(c(2.8, 10.2)),
        mean(c(4.0, 5.8)),
        mean(c(6.2, 8.0)),
        mean(c(8.4, 10.2))),
  y = c(.22, .22, .08, .08, .08) + 0.015,   
  label = c("A priori selection", "Candidate data-driven selection", "Separate covariate lm", "Simultaneous covariate lm", "Simultaneous covariate LASSO")
)

ggplot(
  plot_df,
  aes(x = x_pos, y = type_I, fill = method, pattern = method)
) +
  geom_bar_pattern(
    stat = "identity",
    width = bar_width,
    pattern_colour = "white",
    pattern_fill = "white",
    pattern_angle = 45,
    pattern_density = 0.6,
    pattern_spacing = 0.02,
    color = "black"
  ) +
  geom_segment(aes(y = .22, x = .5, xend = 2.6)) +
  geom_segment(aes(y = .22, x = 2.8, xend = 10.2)) +
  geom_segment(aes(y = .08, x = 4.0, xend = 5.8)) +
  geom_segment(aes(y = .08, x = 6.2, xend = 8.0)) +
  geom_segment(aes(y = .08, x = 8.4, xend = 10.2)) +
  geom_text(
    aes(label = sprintf("%.3f", type_I)),
    vjust = -0.5
  ) +
    geom_text(
    data = segment_labels,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE
  ) +
  labs(x = NULL, y = "Type I Error") +
  scale_y_continuous(
    limits = c(0, max(type_I_summary$type_I) * 1.2),
    breaks = seq(0, max(type_I_summary$type_I) * 1.2, by = 0.05)
  ) +
  # numeric x with custom breaks/labels; gaps are just extra space between positions
  scale_x_continuous(
    breaks = x_breaks,
    labels = x_labels,
    expand = expansion(mult = c(0.02, 0.05)) 
  ) +
  scale_pattern_manual(values = method_patterns) +
  scale_fill_manual(values = method_colors) +
  theme(
    legend.position = "none"
  )

```



```{r}
observations <- d_0 |> 
  group_by(method, n_obs) |> 
  summarise(prop_sig = mean(type_I),
            .groups = "drop") |> 
  ggplot(aes(x = n_obs, y = prop_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(50, 100, 150, 200, 300, 400)) +
  scale_y_continuous(breaks = c(0.05, 0.10, 0.15, 0.20, .25, .30),
                     limits = c(0.03, .30)) +
  labs(x = NULL,
       subtitle = "Number of Observations",
       y = "Type I Error") +
  scale_linetype_manual(values = method_linetypes) +
  scale_linewidth_manual(values = method_linewidths) +
  scale_color_manual(values = method_colors) +
  theme(legend.title = element_blank())


covs <- d_0 |> 
  group_by(method, n_covs) |> 
  summarise(prop_sig = mean(type_I),
            .groups = "drop") |> 
  ggplot(aes(x = n_covs, y = prop_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(4, 8, 12, 16, 20)) +
  scale_y_continuous(breaks = c(0.05, 0.10, 0.15, 0.20, 0.25, .30),
                     limits = c(.03, .30)) +
  labs(y = NULL,
       x = NULL,
       subtitle = "Number of Covariates") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

good_covs <- d_0 |> 
  group_by(method, p_good_covs) |> 
  summarise(prop_sig = mean(type_I),
            .groups = "drop") |> 
  ggplot(aes(x = p_good_covs, y = prop_sig, color = method, linetype = method, 
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(0.25, 0.50, 0.75), labels = c(25, 50, 75)) +
  scale_y_continuous(breaks = c(0.05, 0.10, 0.15, 0.20, .25, .30), 
                     limits = c(.03, .30)) +
  labs(y = "Type I Error",
       x = NULL,
       subtitle = "Percentage of Good Covariates") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

ycor <- d_0 |> 
  group_by(method, r_ycov) |> 
  summarise(prop_sig = mean(type_I),
            .groups = "drop") |> 
  ggplot(aes(x = r_ycov, y = prop_sig, color = method, linetype = method, 
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(0.3, 0.5)) +
  scale_y_continuous(breaks = c(0.05, 0.10, 0.15, 0.20, 0.25, 0.30), 
                     limits = c(.03, .30)) +
  labs(y = NULL,
       x = NULL,
       subtitle = "Y-Covariate Correlation Strength") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

```



```{r}
#| label: fig-type1-panel
#| fig-cap: "Type I error by method and research context. Plots are paneled by aspects of the research context (number of observations, number of covariates, percentage of good covariates (i.e., covariates with non-zero correlations with Y), and Y-covariate correlation strength). Methods are displayed separately by color. Data-driven correlation selection methods that control for X are depicted as dashed lines."
#| fig-height: 6
#| fig-width: 8

(observations + covs)/(good_covs + ycor) +
  plot_layout(guides = "collect") &
  theme(legend.position = "right")
```



```{r}
#| label: fig-bar-2
#| fig-cap: "Type II Error by Method. Average type II error rate across all research settings is displayed for each method separately by color. A priori selection methods are on the left, data-driven selection methods are on the right. Striped shading indicates data-driven selection methods that do not control for X."
#| fig-width: 8.75

type_II_summary <- d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |> 
  group_by(method) |>
  summarise(type_II = mean(type_II, .groups = "drop")) |> 
  mutate(group = case_match(method,
                            "p-hacking" ~ "p-hacking",
                            "No covariates" ~ "No selection",
                            "All covariates" ~ "No selection",
                            "Separate covariate lm" ~ "Separate covariate lm",
                            "Separate covariate lm with X" ~ "Separate covariate lm",
                            "Simultaneous covariate lm" ~ "Simultaneous covariate lm",
                            "Simultaneous covariate lm with X" ~ "Simultaneous covariate lm",
                            "Simultaneous covariate LASSO" ~ "Simultaneous covariate LASSO",
                            "Simultaneous covariate LASSO with X" ~ "Simultaneous covariate LASSO"))

# ---- Parameters
gap_after_idx <- c(2, 4, 6)  
gap_size <- 0.2                
bar_width <- 0.9                


df <- type_II_summary |>
  mutate(method_chr = as.character(method))


n <- nrow(df)
base_pos <- seq_len(n)  

# compute how many gaps precede each bar
gap_count_before <- sapply(base_pos, function(i) sum(gap_after_idx < i))
# add the total gap length before each bar
x_pos <- base_pos + gap_count_before * gap_size

plot_df <- df |>
  mutate(x_pos = x_pos)


x_breaks <- plot_df$x_pos
x_labels <- c("No covariates", "All covariates",
              "Without X", "With X",
              "Without X", "With X",
              "Without X", "With X")

segment_labels <- tibble::tibble(
  x = c(mean(c(0.6, 2.6)),
        mean(c(2.8, 9.2)),
        mean(c(2.8, 4.6)),
        mean(c(5, 6.8)),
        mean(c(7.2, 9))),
  y = c(.50, .50, .40, .40, .40) + 0.015,   
  label = c("A priori selection", "Candidate data-driven selection", "Separate covariate lm", "Simultaneous covariate lm", "Simultaneous covariate LASSO")
)


ggplot(
  plot_df,
  aes(x = x_pos, y = type_II, fill = method, pattern = method)
) +
   geom_bar_pattern(
    stat = "identity",
    width = bar_width,
    pattern_colour = "white",
    pattern_fill = "white",
    pattern_angle = 45,
    pattern_density = 0.6,
    pattern_spacing = 0.02,
    color = "black"
  ) +
  geom_segment(aes(y = .50, x = .6, xend = 2.6)) +
  geom_segment(aes(y = .50, x = 2.8, xend = 9.2)) +
  geom_segment(aes(y = .40, x = 2.8, xend = 4.6)) +
  geom_segment(aes(y = .40, x = 5, xend = 6.8)) +
  geom_segment(aes(y = .40, x = 7.2, xend = 9)) +
  geom_text(
    aes(label = sprintf("%.3f", type_II)),
    vjust = -0.5
  ) +
  geom_text(
    data = segment_labels,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE
  ) +
  labs(x = NULL, y = "Type II Error") +
  scale_y_continuous(
    limits = c(0, max(type_II_summary$type_II) * 1.2),
    breaks = seq(0, max(type_II_summary$type_II) * 1.2, by = 0.05)
  ) +
  # numeric x with custom breaks/labels; gaps are just extra space between positions
  scale_x_continuous(
    breaks = x_breaks,
    labels = x_labels,
    expand = expansion(mult = c(0.02, 0.05))  
  ) +
  scale_pattern_manual(values = method_patterns) +
  scale_fill_manual(values = method_colors) +
  theme(
    legend.position = "none"
  )
```

```{r}
observations_2 <- d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |> 
  group_by(method, n_obs) |> 
  summarise(prop_not_sig = mean(type_II),
            .groups = "drop") |> 
  ggplot(aes(x = n_obs, y = prop_not_sig, color = method, linetype = method, linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(50, 100, 150, 200, 300, 400)) +
  scale_y_continuous(breaks = c(0.10, 0.20, .30, .40, .50, .60, .70, .80),
                    limits = c(0.02, .80)) +
  labs(y = "Type II Error",
       subtitle = "Number of Observations",
       x = NULL) +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

covs_2 <- d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |>  
  group_by(method, n_covs) |> 
  summarise(prop_not_sig = mean(type_II),
            .groups = "drop") |> 
  ggplot(aes(x = n_covs, y = prop_not_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(4, 8, 12, 16, 20)) +
  scale_y_continuous(breaks = c(0.20, .30, .40, .50),
                    limits = c(0.2, .50)) +
  labs(y = NULL,
       x = NULL,
       subtitle = "Number of Covariates") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

good_covs_2 <-d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |> 
  group_by(method, p_good_covs) |> 
  summarise(prop_not_sig = mean(type_II),
            .groups = "drop") |> 
  ggplot(aes(x = p_good_covs, y = prop_not_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(0.25, 0.50, 0.75), labels = c(25, 50, 75)) +
  scale_y_continuous(breaks = c(0.20, .30, .40, .50 ),
                    limits = c(0.2, .50)) +
  labs(y = "Type II Error",
       x = NULL,
       subtitle = "Percentage of Good Covariates") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank())

ycor_2 <- d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |> 
  group_by(method, r_ycov) |> 
  summarise(prop_not_sig = mean(type_II),
            .groups = "drop") |> 
  ggplot(aes(x = r_ycov, y = prop_not_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(0.3, 0.5)) +
  scale_y_continuous(breaks = c(0.20, .30, .40, .50),
                    limits = c(0.2, .52)) +
  labs(y = NULL,
       x = NULL,
       subtitle = "Y-Covariate Correlation Strength") +
  scale_linetype_manual(values = method_linetypes) +
  scale_linewidth_manual(values = method_linewidths) +
  scale_color_manual(values = method_colors) +
  theme(legend.title = element_blank())

b_x <- d_02 |>
  bind_rows(d_05) |> 
  filter(method != "p-hacking") |> 
  group_by(method, b_x) |> 
  summarise(prop_not_sig = mean(type_II),
            .groups = "drop") |> 
  ggplot(aes(x = b_x, y = prop_not_sig, color = method, linetype = method,
             linewidth = method)) + 
  geom_line() +
  scale_x_continuous(breaks = c(0.2, 0.5)) +
  scale_y_continuous(breaks = c(0.10, 0.20, .30, .40, .50, .60, .70, .80), 
                     limits = c(0.02, .80)) +
  labs(y = "Type II Error",
       x = NULL,
       subtitle = "Population Parameter for X") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  scale_linewidth_manual(values = method_linewidths) +
  theme(legend.title = element_blank(),
        legend.position = "none")

```



```{r}
#| label: fig-panel-2
#| fig-cap: "Type II error by method and research context. Plots are paneled by aspects of the research context (number of observations, number of covariates, percentage of good covariates covariates (i.e., covariates with non-zero correlations with Y), and Y-covariate correlation strength), and Y-covariate correlation strength, and population parameter for X). Methods are displayed separately by color. Data-driven correlation selection methods that control for X are depicted as dashed lines."
#| fig-height: 9
#| fig-width: 7.5

  (observations_2 + covs_2)/(good_covs_2 + ycor_2)/(b_x + plot_spacer()) +
  plot_layout(guides = "collect") &
  theme(legend.position = "right")
```





```{r}


est_d_0 <- d_full |> 
  filter(b_x == 0) |> 
  filter(estimate > -0.5 & estimate < .5) |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black") +
  scale_x_continuous(limits = c(-0.5, 0.5), breaks = seq(-0.5, 0.5, by = 0.5)) +
  labs(y = "Density",
       x = "Estimate") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) 

est_d_02 <-d_full |> 
  filter(b_x == 0.2) |> 
  filter(estimate > -0.3 & estimate < .7) |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0.2, linetype = "dotted") +
  scale_x_continuous(limits = c(-0.3, 0.7), breaks = c(-0.3, 0.2, 0.7)) +
  labs(y = "Density",
       x = "Estimate") +
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  theme(legend.position = "none")

est_d_05 <- d_full |> 
  filter(b_x == 0.5) |> 
  filter(estimate > 0 & estimate < 1) |> 
  ggplot(aes(x = estimate, color = method, linetype = method)) +
  geom_density(alpha = 0.5) +
  geom_vline(xintercept = 0.5, linetype = "dotted") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  labs(y = "Density",
       x = "Estimate") + 
  scale_linetype_manual(values = method_linetypes) +
  scale_color_manual(values = method_colors) +
  theme(legend.position = "none")
```

```{r}
#| label: fig-distribution-bx
#| fig-cap: "Sampling Distribution for Population Parameter Estimates."
#| fig-height: 8
#| code-fold: true

est_d_0 / est_d_02 / est_d_05
```

